graph TB;
    subgraph ARCHS
    FILTER-->ARCH_SPLIT;
    ARCH-->FILTER{FILTER};
    ARCH_SPLIT-->ISA;
    ARCH_SPLIT-->PLATFORM;
    end

    subgraph Sources and objects
    SRCS;
    AM_SRCS;
    OBJS;
    LIBS;
    LINKAGE;
    end

    subgraph Cross compile
    cross["CROSS_COMPILE"];
    cross-->CC;
    cross-->CXX;
    cross-->AS;
    cross-->LD;
    cross-->OBJCOPY;
    cross-->OBJDUMP;
    end

    subgraph Flags
    CFLAGS
    CXXFLAGS
    LDFLAGS
    NEMUFLAGS
    end
